#!/bin/bash -l
#
#SBATCH --gres=gpu:a40:1
#SBATCH --time=24:00:00
#SBATCH --export=NONE
#SBATCH --job-name=benchmark-uma

ASE_WRAPPER=/home/hpc/b146dc/b146dc13/progs/MLIP_vib_benchmarking_project/ASE_wrapper/dynamic.py
INPUT_FILE=/home/hpc/b146dc/b146dc13/work-atuin/MLIP_vib_bench/uma/uma_md.inp
ENV=/home/vault/b146dc/b146dc13/envs/uma

unset SLURM_EXPORT_ENV

# Deactivate the current Python
module unload python

# Activate the virtual environment
echo ""
echo "Activating the virtual environment for UMA at $ENV ..."
echo ""
source $ENV/bin/activate

# Add pyhton3.12 from the virtual environment to the PATH
export PATH=$ENV/bin:$PATH

# Run the ASE wrapper dynamic.py
python3.12 $ASE_WRAPPER -input=$INPUT_FILE

